[font]
size = 9.9

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[colors.primary]
background = "0x1E1E2E"
foreground = "0xCDD6F4"

[colors.cursor]
cursor = "#b4befe"

[window]
opacity = 1
dynamic_title = true
dynamic_padding = true
decorations = "none"

[cursor]
blink_interval = 500

[cursor.style]
shape = "Beam"
blinking = "Always"

[keyboard]
# bindings = [
# { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
# { key = "M", mods = "Control|Shift", action = "ToggleMaximized"}
# ]

[terminal]
# [env]
# TERM = "screen-256color"

[terminal.shell]
program = "/usr/bin/tmux"
